### ISSUE TITLE
Missing Battery and Bluetooth icons

### ISSUE THREAD

**Issue by orschiro** [nathandyer/elementary-dropbox-mods#2]
Hi @nathandyer,

Is it possible that your script conflicts with the native battery and bluetooth icons?

Since I installed the script, my battery and bluetooth icons are no longer shown in wingpanel.

Thanks for your help!

Robert

**Comment by nathandyer** [comment]
Hi @orschiro!

My script shouldn't cause any issues with the battery or bluteooth icons in Wingpanel. If you install the custom Dropbox icons it regenerates the icon cache, but it doesn't delete or modify any of the icons, so that shouldn't affect it. I have used this script on three different computers over the past few weeks and haven't noticed the bluetooth or battery icons disappearing in any of them.

Have you installed any new themes or applied any other mods recently?

Good luck! Sorry your indicators have disappeared.

Cheers,
-Nathan

**Comment by orschiro** [comment]
@nathandyer 

I appreciate your response! In the meantime I have been able to find a related bug report which I will follow on this: https://bugs.launchpad.net/wingpanel/+bug/1391618

**Comment by orschiro** [comment]
Problem solved. For some reasons, the indicators were just not installed: https://bugs.launchpad.net/wingpanel/+bug/1391618/comments/4
